### ISSUE TITLE
Contribution Reward Application

### ISSUE THREAD

**Issue by vinchua** [Ascend-Huawei/Community_Contribution_Reward#1]
Merged Pull Request ID/Link: 
- https://gitee.com/ascend/samples/tree/master/python/contrib/DIY_200DK_RC_Car  (https://gitee.com/ascend/samples/pulls/671)
- https://gitee.com/ascend/samples/tree/master/python/level1_single_api/5_200dk_peripheral (https://gitee.com/ascend/samples/pulls/614)

Claim: By submitting this issue to enter the 'community contribution competition', I confirm have read and agree with [ASCEND COMMUNITY CONTRIBUTION COMPETITION RULE](https://github.com/Ascend-Huawei/Community_Contribution_Reward/blob/main/ASCEND_COMMUNITY_CONTRIBUTION_COMPETITION_RULES.md)

**Comment by ascendhuawei** [comment]
Hi, @vinchua , Congratulations! We have reviewed and approved your application. Will contact you by email for details.
