### ISSUE TITLE
Contribution Reward Application

### ISSUE THREAD

**Issue by StevenSong-sTs** [Ascend-Huawei/Community_Contribution_Reward#2]
Merged Pull Request ID/Link: 
[https://gitee.com/ascend/samples/tree/master/python/contrib/DIY_200DK_RC_Car  
(https://gitee.com/ascend/samples/pulls/671)]

Project: Hand Gesture Controlled Robot Pet
Contributor: Charley, Dianna, Steven, Sunny, Violet

Claim: By submitting this issue to enter the 'community contribution competition', I confirm have read and agree with [ASCEND COMMUNITY CONTRIBUTION COMPETITION RULE](https://github.com/Ascend-Huawei/Community_Contribution_Reward/blob/main/ASCEND_COMMUNITY_CONTRIBUTION_COMPETITION_RULES.md)

**Comment by ascendhuawei** [comment]
Hi, 
Thanks for the application. We will process and contact you via email
